version: "3"

services:

  gaucamole:
    container_name: guacamole
    image: maxwaldorf/guacamole
    restart: unless-stopped
    ports:
    - 8080:8080
    volumes:
    - /opt/docker/guacamole:/config
    environment:
    - EXTENSIONS=auth-totp




