version: "3"

services:

  unifi:
    container_name: unifi-6.5.54
    image: jacobalberty/unifi:v6.4.54
    restart: unless-stopped
    network_mode: "host"
    volumes:
    - /opt/docker/unifi-6.4.54:/unifi
    environment:
    - TZ=Europe/Amsterdam


