version: "3"

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/docker/portainer/data:/data


  telegraf:
    container_name: telegraf
    image: telegraf:1.17.2
    restart: unless-stopped
    volumes:
    - /opt/docker/telegraf:/etc/telegraf:ro
    - /:/hostfs:ro
    environment:
    - HOST_ETC=/hostfs/etc
    - HOST_PROC=/hostfs/proc
    - HOST_SYS=/hostfs/sys
    - HOST_VAR=/hostfs/var
    - HOST_RUN=/hostfs/run
    - HOST_MOUNT_PREFIX=/hostfs


